### ISSUE TITLE
Hostmanager Plugin Installation

### ISSUE THREAD

**Issue by bennias** [DenizTemizer/wt3box#1]
### Vagrant version

Vagrant 2.0.0

### Operating system

macOS Sierra 10.12.6

### Expected behavior

`vagrant plugin install vagrant-hostmanager` should install the plugin

### Actual behavior
Executing:
`vagrant plugin install vagrant-hostmanager`

Resolves in:
```
Installing the vagrant-hostmanager plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/ 
```

### Solution - _that worked for me_
**Disabling IPv6** | according to https://github.com/hashicorp/vagrant/issues/8795
`networksetup -setv6off Wi-Fi`

**Comment by DenizTemizer** [comment]
Not a issue with the project but vagrant itself.
